### ISSUE TITLE
When html conent contain string in [],  wiil error

### ISSUE THREAD

**Issue by krircc** [longshorej/csi#9]
I find When html conent contain string in [],  been known as Directives,  but cannot be parsed
the commend `fsw csi src target/dist --ext .html` will error. how can i process it?

**Comment by longshorej** [comment]
Thanks for filing @krircc. Could you include a minimal reproducer (the html files) when you have a moment? I'm not currently able to reproduce but want to make sure I'm not missing anything.

**Comment by krircc** [comment]
@longshorej sorry, It 's my error, now I know , because "cfg"in [],been known as Directives,  but cannot be parsed. I now find can use escapes to process it. 
thanks!
